blank_issues_enabled: false

contact_links:
  - name: Project Discussions
    url: https://github.com/RITIKESHDUTT/gLexShrD/discussions
    about: Share ideas, ask questions, report bugs, or suggest improvements.