[env]
VK_INSTANCE_LAYERS = "VK_LAYER_KHRONOS_validation"
VK_KHRONOS_VALIDATION_MESSAGE_ID_FILTER = "BestPractices-PipelineBarrier-unneeded-QFOT"
VK_KHRONOS_VALIDATION_REPORT_FLAGS = "error,warn,perf"
VK_KHRONOS_VALIDATION_GPU_ASSISTED = "true"
VK_KHRONOS_VALIDATION_GPU_ASSISTED_RESERVE_BINDING_SLOT = "true"
VK_KHRONOS_VALIDATION_VALIDATE_BEST_PRACTICES = "true"
VK_KHRONOS_VALIDATION_SYNCHRONIZATION_VALIDATION = "true"
VK_KHRONOS_VALIDATION_OBJECT_LIFETIMES = "true"
VK_KHRONOS_VALIDATION_VALIDATE_SYNC = "true"
VK_KHRONOS_VALIDATION_DEBUG_ACTION = "VK_DBG_LAYER_ACTION_LOG_MSG,VK_DBG_LAYER_ACTION_DEBUG_OUTPUT"
"VK_LAYER_KHRONOS_validation.log_filename" = "validation.log"